### ISSUE TITLE
Masquer le bouton "Flash" en mode DataWedge

### ISSUE THREAD

**Issue by abelatar** [enioka-Haute-Couture/enioka_scan#114]
Hello @marcanpilami 
Dans la version actuelle de la librairie 2.3.7 qui supporte DataWedge, j'ai remarqué que le bouton de flash est toujours affiché, même lorsque l'on est en mode DataWedge. Étant donné que la fonctionnalité de flash n'est pas nécessaire en mode DataWedge, il serait judicieux de la cacher automatiquement.

![Screen_Mobiprep_ButtonFlash](https://github.com/enioka-Haute-Couture/enioka_scan/assets/94049129/3bed6829-eb87-4475-b2e0-14cd442b83a0)

**Comment by marcanpilami** [comment]
Bonjour ! Ce n'est pas un flash. C'est le contrôle de l'illumination. Il se trouve que l'illumination utilise le flash pour les appareils photo, mais c'est un concept plus large. Pour le TC27, l'illumination est un fond rouge généré par le laser de balayage. C'est très utile pour les scans en faible luminosité. Ce bouton permet de l'activer ou de le désactiver.

A noter que le choix d'avoir ce bouton présent dans ton layout est totalement ton choix.
