### ISSUE TITLE
 Plantage après plusieurs scan avec la librairie 

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#138]
Bonjour @DaSpood, @marcanpilami ,

Lorsque nous exécutons plusieurs scans rapides successifs en utilisant la librairie au sein de notre application, notamment sur les appareils Xcover 4S et 5, nous rencontrons un problème d'instabilité qui conduit à un crash de l'application après une dizaine de scans. Voici les traces que j'ai pu récupérer suite à l'arrêt inattendu de l'application : 

![t2](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/a7243aa0-c209-42ae-b213-fcd9504302a3)

**Étapes pour reproduire :**
Ouvrez l'application sur un Xcover 4S et 5 et accédez à la fonction de scan.
A bout d'une dizaine de scan l'application crash

**Emplacement de Plantage**
 
![x1](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/01d42759-f0f3-4d20-a86d-fa401e2f8a36)

**Proposition pour une solution**
Je pense qu'il faut changer : 

 `if (image.getPlanes()[0].getPixelStride() != 1) {
                throw new RuntimeException("not a luminance buffer");
 }`
 par 
`if (image.getPlanes()[0].getBuffer() != null) {
                throw new RuntimeException("not a luminance buffer");
 }`

**Comment by DaSpood** [comment]
Normalement corrigé avec la 2.4.1, rouvrir une issue si nécessaire
