### ISSUE TITLE
Plantage lorsque j'essai de quitter une Activity / Camera 2

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#139]
Bonjour @DaSpood, @marcanpilami ,

Lorsque nous exécutons par foi un scan en utilisant la librairie au sein de notre application, notamment sur les appareils Xcover 4S et 5, nous rencontrons un problème d'instabilité qui conduit à un crash de l'application. Voici les traces que j'ai pu récupérer suite à l'arrêt inattendu de l'application :

 ![b3](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/c76c1889-dafd-460d-b64f-597a63914b29)
 
**Proposition pour une solution**
Je pense qu'il faut ajouter un test if captureRequestBuilder != null entre ce bloc : 

 `captureRequestBuilder.removeTarget(this.camPreviewSurfaceView.getHolder().getSurface());
captureRequestBuilder = null;`

**Comment by fmanoir** [comment]
Même souci que #134 avec A34 +  Xcover 4S et Xcover 5

**Comment by DaSpood** [comment]
Normalement corrigé avec la 2.4.1, rouvrir une issue si nécessaire
