### ISSUE TITLE
 Plantage lorsque j'essai de resume activity / Camera 1

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#140]
Bonjour @DaSpood, @marcanpilami ,

Lorsque nous exécutons par fois un scan en utilisant la librairie au sein de notre application, notamment sur les appareils Xcover 4S et 5, nous rencontrons un problème d'instabilité qui conduit à un crash de l'application. Voici les traces que j'ai pu récupérer suite à l'arrêt inattendu de l'application :

 
![b5](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/88226bc9-e951-4e29-9ec1-9f89c2de110d)

**Proposition pour une solution**
Je pense qu'il faut assurer que l'instance this.cam not null

**Comment by DaSpood** [comment]
Normalement corrigé avec la 2.4.1, rouvrir une issue si nécessaire
