### ISSUE TITLE
FLASH s'allume + Plantage  pour un changment de rotation de portrait vers landscape

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#141]
Lorsqu'il y a un changement de rotation de portrait vers landscape, le FLASH s'allume.

Voici les traces que j'ai pu récupérer suite à l'arrêt inattendu de l'application :

![t1](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/093a7227-d877-4194-a6b4-53dcbad9ebc8)

**Je pense que l'instance caméra (cam) devient nulle donc il ne peut pas récupérer les paramètres**

**Comment by fmanoir** [comment]
C'est même crach liée au #140

**Comment by fmanoir** [comment]
Pour le même scénario il y a aussi par fois, un autre crach sur A34 : 

![t3](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/b50d089f-97a3-4ddd-a3f2-c19bcd22efb3)

**Comment by DaSpood** [comment]
Normalement corrigé avec la 2.4.1, rouvrir une issue si nécessaire
