### ISSUE TITLE
Amélioration : Réinitialiser l'emplacement de la target

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#148]
Bonjour, 

Est-ce qu'il serait envisageable d'apporter une petite amélioration lorsque allowTargetDrag est activé ? qui nous permet de réinitialiser l'emplacement de target (Rectangle rouge).

**Problème :** 

Lorsque je modifie l'emplacement de "target" avec un view au-dessus de camPreviewSurfaceView avec hauteur changeable, le target se cache derrière le view.

![xxx](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/fcea5e10-25b3-4068-8fac-3316dfde11c2)

**Proposition d'une solution :** 

Je crois qu'il est suffisant de nous donner la possibilité de modifier la Preferences ("y" + getDeviceOrientationRelativeToDeviceNaturalOrientation() ) avec View.invalidate(); ce nous permet de placer target programmatically

**Comment by DaSpood** [comment]
L'ajout d'une méthode publique de la CameraBarcodeScanView (donc accessible via `findViewById(cameraViewId)` depuis l’activité) "resetTargetPosition()" qui réinitialiserait la position du rectangle (et aussi les preferences sauvegardées) au centre de l'image ferait-elle l'affaire ?

**Comment by fmanoir** [comment]
Merci fonctionne parfaitement
