### ISSUE TITLE
Flash s'allume automatiquement avec Camera 1 

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#151]
Bonjour, 

Pour contourner le problème sur #150 temporairement, nous avons mis en place une solution temporaire de fixer forceCameraApiVersion = V1 mais nous trouvons un autre problème avec Xcover 5, Si nous modifions l'organisation portrait-> landscape avec la caméra V1, le flash s'allume automatiquement.

**Comment by DaSpood** [comment]
J'essaierai de reproduire ce comportement sur mon XCover 4S, je n'ai malheureusement pas de XCover 5 pour tester sur le meme appareil.

**Comment by fmanoir** [comment]
Oui, merci je l'ai réglé avec un test sur  onConfigurationChanged
