### ISSUE TITLE
Crash on Athesia SPA43LTE when using the legacy API camera on the demo app.

### ISSUE THREAD

**Issue by VincentKobz** [enioka-Haute-Couture/enioka_scan#170]
`java.lang.RuntimeException: Fail to connect to camera service`
`java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference`

This crash occurs when trying to access the scanner camera of the `Athesia SPA43LTE` using the button on the demo app.
The camera API used is the legacy Camera of `android.hardware`.
When the camera is instantiated automatically (when it is the only provider available), this crash does not occur.

**Comment by DaSpood** [comment]
Add to the list of known issues in the documentation, then close the issue: we won't fix it for now but we want to keep it documented somewhere to come back to it if needed.
