### ISSUE TITLE
problème vitesse de scan Datawedge car la lib semble parfois faire appel au Profil Datawedge par défaut (Profile0) en plus du profil généré pour l'app

### ISSUE THREAD

**Issue by mgu78** [enioka-Haute-Couture/enioka_scan#172]
exemple d'une app qui ne fait appel qu'a son profil Datawedge
![tran2](https://github.com/enioka-Haute-Couture/enioka_scan/assets/1768842/2f330457-ffb3-4909-a1ec-9e4da27d2054)

app avec des appel a son profil + le profil par défaut Profile0 cela a pour effet de ralentir la cadence de scan sur l'app
![tran1](https://github.com/enioka-Haute-Couture/enioka_scan/assets/1768842/20b15f23-1ee5-4f89-9fdc-acaf83e576bc)
le souci c'est ici MobiCop reçois un intent (com.symbol.datawedge.api.SWITCH_SCANNER_PARAMS) pour cela il change le profile mobiCop vers profile0
![xxa](https://github.com/enioka-Haute-Couture/enioka_scan/assets/1768842/a34acc2b-61b0-480f-8541-eab52c8adef9)

**Comment by fmanoir** [comment]
Problème résolu.
Merci @DaSpood
