### ISSUE TITLE
 Pop-Up Saisie manuelle 

### ISSUE THREAD

**Issue by fmanoir** [enioka-Haute-Couture/enioka_scan#174]
Bonjour @DaSpood

Est-il possible d'ajouter un paramètre dans le constructeur pour changer la couleur du bouton et l'input?

Le style de nos applications est bleu. Il ne nous reste que cette Pop-Up Saisie manuelle  en Verte :

![Screenshot_20240418_132344](https://github.com/enioka-Haute-Couture/enioka_scan/assets/24919155/c8fe3f48-9765-44dc-8597-2f3504f176a0)

**Comment by fmanoir** [comment]
Bonjour @DaSpood 

Oui c'est Ok pour barre horizontale  avec colorAccent  
mais c'est KO pour le bouton avec (@+id/scanner_manual_bt_ok) , si possible de le modifier pour qu'il avoir colorAccent  aussi  par défaut 

Merci.

**Comment by DaSpood** [comment]
Bonjour,

Je me permet de fermer cette issue qui est sensee etre resolue depuis la release 3.0. En cas de probleme sur le meme sujet n'hesitez pas a creer une nouvelle issue et a referencer celle ci.
