### ISSUE TITLE
Camera scanner is not working properly on HoneyWell EDA52

### ISSUE THREAD

**Issue by VincentKobz** [enioka-Haute-Couture/enioka_scan#179]
When using the HoneyWell EDA52, the camera scanner functionality is not working properly.
Although the activity can start, and the camera feedback is available, it is impossible to scan barcodes.

`Access denied finding property "vendor.camera.aux.packagelist"`

**Comment by DaSpood** [comment]
Device-specific issue, won't fix for now. Will re-open if real users express the need for it.
