### ISSUE TITLE
Flashlight turns off when changing screen orientation on EDA52

### ISSUE THREAD

**Issue by VincentKobz** [enioka-Haute-Couture/enioka_scan#185]
Description:
- When you enable flashlight on camera view, it will automatically turn off when screen orientation changes.

Branch:
- Occurs on [app-demo branch](https://github.com/enioka-Haute-Couture/enioka_scan/tree/129-demo-app-redesign).

Device:
- HoneyWell EDA52

**Comment by DaSpood** [comment]
Add to the list of known issues in the documentation, then close the issue: we won't fix it for now but we want to keep it documented somewhere to come back to it if needed.

**Comment by VincentKobz** [comment]
The bug was fixed by https://github.com/enioka-Haute-Couture/enioka_scan/pull/182, probably with the screen orientation change fix. I will close this issue.
