### ISSUE TITLE
Camera: Allow moving and resizing target from code

### ISSUE THREAD

**Issue by DaSpood** [enioka-Haute-Couture/enioka_scan#188]
Related to #187 

Add methods to the Camera API to:
- move the target up and down
- resize the target (sometimes it is too narrow and depending on use cases a more square target may be better)

**Comment by DaSpood** [comment]
@VincentKobz Si tu es a cours de sujets a traiter, tu peux y jeter un oeil ?

**Comment by VincentKobz** [comment]
> @VincentKobz Si tu es a cours de sujets a traiter, tu peux y jeter un oeil ?

Je m'en occupe

**Comment by DaSpood** [comment]
Resolved by #190
