### ISSUE TITLE
Demo app settings activity should dynamically list available SDKs

### ISSUE THREAD

**Issue by marcanpilami** [enioka-Haute-Couture/enioka_scan#80]
Currently, the settings activity of the demo app is completely hard-coded, meaning every SDK is included regardless of whether or not they are available to the app (this will become an issue after #128).

The settings activity should dynamically detect available providers and only list those.
The main activity should only add available providers to the search options and ignore unavailable ones even if they did exist in the persisted preferences.

It would also be useful to add a more human-readable description or name for all SDKs besides their identifier key to improve display in the settings activity.

**Comment by DaSpood** [comment]
Resolved by #180
