### ISSUE TITLE
Add a focus on touch location mode (V2 only)

### ISSUE THREAD

**Issue by marcanpilami** [enioka-Haute-Couture/enioka_scan#86]
Should be allowable by an attribute. Disabled by default.

**Comment by DaSpood** [comment]
@marcanpilami as of #120, the AutoFocus is force-triggered whenever the target is moved (or just tapped) for both CameraV1 and CameraV2, is a separate touch-to-focus not redundant (as it will override / be overridden by the target area whenever touched) ?
